### ISSUE TITLE
Set up eslint

### ISSUE THREAD

**Issue by attaboy** [ellipsis-ai/behaviors#5]
- add a package.json config for node
- install eslint
- set up configuration
- write a script we can run
- set up sample githooks

**Comment by attaboy** [comment]
@andrewcatton Turns out we can't lint our current `function.js` exports because they're not valid JavaScript syntax.

Would it be tricky to change our export format to use node module style? This is what we do currently:

```
function(ellipsis) {
  // […]
}
```

If we change it to this, it would be valid JS (and as a bonus, exportable as an npm package):

```
module.exports = function(ellipsis) {
  // […]
};
```

**Comment by andrewcatton** [comment]
Certainly doable. I was wondering if there was any downside to it in terms of user expectations – like do we expect anyone to use them this way (as an npm package)?

**Comment by attaboy** [comment]
I don't expect it, no, although it sort of hints at the possibility that you could write a complex behavior that has multiple modules. (Maybe we would even want that someday?)

One nice thing about it is that it does reaffirm that you're writing/reading code for the node.js environment.

If we want a more neutral-looking but still-valid syntax, we could just add `return` at the beginning so the file returns a function:

```
return function(ellipsis) {
…
};
```
